# Configuration du CLI Diesel
# Documentation officielle :
# https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
# Emplacement du fichier généré contenant le schéma Rust à partir de la DB
file = "src/schema.rs"

# Traits supplémentaires dérivés pour les types personnalisés générés
custom_type_derives = [
    "diesel::query_builder::QueryId",
    "Clone"
]

[migrations_directory]
# Chemin RELATIF vers les migrations (à versionner avec le projet)
# Important : ne jamais mettre un chemin absolu ici
dir = "migrations"